from tkinter import*
from tkinter import messagebox
from tkinter import ttk
import sqlite3
class studentpanel:
    def __init__(self):
        self.a=Tk()
        l=Label(text='Name')
        l.pack()
        self.e=Entry()
        self.e.pack()
        l1=Label(text='Email')
        l1.pack()
        self.e1=Entry()
        self.e1.pack()
        l2=Label(text='Password')
        l2.pack()
        self.e2=Entry()
        self.e2.pack()
        l3=Label(text='Roll No')
        l3.pack()
        self.e3=Entry()
        self.e3.pack()
        l4=Label(text='Branch')
        l4.pack()
        self.e4=Entry()
        self.e4.pack()
        l5=Label(text='Stream')
        l5.pack()
        self.e5=Entry()
        self.e5.pack()
        l6=Label(text='City')
        l6.pack()
        self.e6=Entry()
        self.e6.pack()
        b=Button(text='signup',command=self.signup)
        b.pack()
        b1=Button(text='login',command=self.login)
        b1.pack()
    def signup(self):
        db=sqlite3.connect('attn.db')
        cr=db.cursor()
        cr.execute(f'''insert into student values('{self.e.get()}','{self.e1.get()}','{self.e2.get()}','{self.e3.get()}','{self.e4.get()}','{self.e5.get()}','{self.e6.get()}') ''')
        db.commit()
        messagebox.showinfo('success','User create you can how login')
##        self.a.destroy()
##        self.login()
        print("signup")
    def login(self):
        
##        if self.a:
        self.a.destroy()
        self.b=Tk()
        l1=Label(text='Email')
        l1.pack()
        self.e1=Entry()
        self.e1.pack()
        l2=Label(text='Password')
        l2.pack()
        self.e2=Entry()
        self.e2.pack()
        b1=Button(text='Login',command=self.login1)
        b1.pack()

    def login1(self):
        db=sqlite3.connect('attn.db')
        cr=db.cursor()
        cr.execute(f'''select* from student where email='{self.e1.get()}' and password='{self.e2.get()}' ''')
        data=cr.fetchone()
        if data:
            self.b.destroy()
            self.c=Tk()
            l=Label(text="Hello" +data[0])
            l.pack()
            notebook=ttk.Notebook()
            frame=Frame(self.c,bg="red",padx=120,pady=150)
            l1=Label(frame,text="Welcome")
            l1.pack()
            frame.pack()
            frame1=Frame(self.c,bg="yellow",padx=120,pady=200)
            l2=Label(frame1,text="Thanks")
            l2.pack()
            frame1.pack()
            notebook.add(frame,text="Students")
            notebook.add(frame1,text="attendance")
            notebook.pack()
        else:
            messagebox.showinfo('failure','wrong creadentails')


